/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as StorefrontRouteRouteImport } from './routes/_storefront/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StorefrontIndexRouteImport } from './routes/_storefront/index'
import { Route as StorefrontOrderConfirmedRouteImport } from './routes/_storefront/order-confirmed'
import { Route as StorefrontCheckoutRouteImport } from './routes/_storefront/checkout'
import { Route as StorefrontAboutRouteImport } from './routes/_storefront/about'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as StorefrontProductsIndexRouteImport } from './routes/_storefront/products/index'
import { Route as StorefrontCategoriesIndexRouteImport } from './routes/_storefront/categories/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUploadAuthRouteImport } from './routes/api/admin/upload-auth'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'
import { Route as AdminCategoriesNewRouteImport } from './routes/admin/categories/new'
import { Route as StorefrontProductsSlugRouteImport } from './routes/_storefront/products/$slug'
import { Route as StorefrontCategoriesSlugRouteImport } from './routes/_storefront/categories/$slug'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products/$id.edit'
import { Route as AdminCategoriesIdEditRouteImport } from './routes/admin/categories/$id.edit'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontRouteRoute = StorefrontRouteRouteImport.update({
  id: '/_storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StorefrontIndexRoute = StorefrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorefrontRouteRoute,
} as any)
const StorefrontOrderConfirmedRoute =
  StorefrontOrderConfirmedRouteImport.update({
    id: '/order-confirmed',
    path: '/order-confirmed',
    getParentRoute: () => StorefrontRouteRoute,
  } as any)
const StorefrontCheckoutRoute = StorefrontCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StorefrontRouteRoute,
} as any)
const StorefrontAboutRoute = StorefrontAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StorefrontRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StorefrontProductsIndexRoute = StorefrontProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => StorefrontRouteRoute,
} as any)
const StorefrontCategoriesIndexRoute =
  StorefrontCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => StorefrontRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadAuthRoute = ApiAdminUploadAuthRouteImport.update({
  id: '/api/admin/upload-auth',
  path: '/api/admin/upload-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesNewRoute = AdminCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StorefrontProductsSlugRoute = StorefrontProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => StorefrontRouteRoute,
} as any)
const StorefrontCategoriesSlugRoute =
  StorefrontCategoriesSlugRouteImport.update({
    id: '/categories/$slug',
    path: '/categories/$slug',
    getParentRoute: () => StorefrontRouteRoute,
  } as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIdEditRoute = AdminCategoriesIdEditRouteImport.update({
  id: '/categories/$id/edit',
  path: '/categories/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/verify': typeof AuthVerifyRoute
  '/about': typeof StorefrontAboutRoute
  '/checkout': typeof StorefrontCheckoutRoute
  '/order-confirmed': typeof StorefrontOrderConfirmedRoute
  '/': typeof StorefrontIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/$slug': typeof StorefrontCategoriesSlugRoute
  '/products/$slug': typeof StorefrontProductsSlugRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/admin/upload-auth': typeof ApiAdminUploadAuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/categories': typeof StorefrontCategoriesIndexRoute
  '/products': typeof StorefrontProductsIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/verify': typeof AuthVerifyRoute
  '/about': typeof StorefrontAboutRoute
  '/checkout': typeof StorefrontCheckoutRoute
  '/order-confirmed': typeof StorefrontOrderConfirmedRoute
  '/': typeof StorefrontIndexRoute
  '/admin': typeof AdminIndexRoute
  '/categories/$slug': typeof StorefrontCategoriesSlugRoute
  '/products/$slug': typeof StorefrontProductsSlugRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/admin/upload-auth': typeof ApiAdminUploadAuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/categories': typeof StorefrontCategoriesIndexRoute
  '/products': typeof StorefrontProductsIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_storefront': typeof StorefrontRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_storefront/about': typeof StorefrontAboutRoute
  '/_storefront/checkout': typeof StorefrontCheckoutRoute
  '/_storefront/order-confirmed': typeof StorefrontOrderConfirmedRoute
  '/_storefront/': typeof StorefrontIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_storefront/categories/$slug': typeof StorefrontCategoriesSlugRoute
  '/_storefront/products/$slug': typeof StorefrontProductsSlugRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/admin/upload-auth': typeof ApiAdminUploadAuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_storefront/categories/': typeof StorefrontCategoriesIndexRoute
  '/_storefront/products/': typeof StorefrontProductsIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/verify'
    | '/about'
    | '/checkout'
    | '/order-confirmed'
    | '/'
    | '/admin/'
    | '/categories/$slug'
    | '/products/$slug'
    | '/admin/categories/new'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/api/admin/upload-auth'
    | '/api/auth/$'
    | '/categories'
    | '/products'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/categories/$id/edit'
    | '/admin/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/verify'
    | '/about'
    | '/checkout'
    | '/order-confirmed'
    | '/'
    | '/admin'
    | '/categories/$slug'
    | '/products/$slug'
    | '/admin/categories/new'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/api/admin/upload-auth'
    | '/api/auth/$'
    | '/categories'
    | '/products'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/categories/$id/edit'
    | '/admin/products/$id/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_storefront'
    | '/admin'
    | '/_auth/login'
    | '/_auth/verify'
    | '/_storefront/about'
    | '/_storefront/checkout'
    | '/_storefront/order-confirmed'
    | '/_storefront/'
    | '/admin/'
    | '/_storefront/categories/$slug'
    | '/_storefront/products/$slug'
    | '/admin/categories/new'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/api/admin/upload-auth'
    | '/api/auth/$'
    | '/_storefront/categories/'
    | '/_storefront/products/'
    | '/admin/categories/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/categories/$id/edit'
    | '/admin/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  StorefrontRouteRoute: typeof StorefrontRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiAdminUploadAuthRoute: typeof ApiAdminUploadAuthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_storefront': {
      id: '/_storefront'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StorefrontRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_storefront/': {
      id: '/_storefront/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StorefrontIndexRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/_storefront/order-confirmed': {
      id: '/_storefront/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof StorefrontOrderConfirmedRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/_storefront/checkout': {
      id: '/_storefront/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StorefrontCheckoutRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/_storefront/about': {
      id: '/_storefront/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StorefrontAboutRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_storefront/products/': {
      id: '/_storefront/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof StorefrontProductsIndexRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/_storefront/categories/': {
      id: '/_storefront/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof StorefrontCategoriesIndexRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-auth': {
      id: '/api/admin/upload-auth'
      path: '/api/admin/upload-auth'
      fullPath: '/api/admin/upload-auth'
      preLoaderRoute: typeof ApiAdminUploadAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/new': {
      id: '/admin/categories/new'
      path: '/categories/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AdminCategoriesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_storefront/products/$slug': {
      id: '/_storefront/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof StorefrontProductsSlugRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/_storefront/categories/$slug': {
      id: '/_storefront/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof StorefrontCategoriesSlugRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/$id/edit': {
      id: '/admin/categories/$id/edit'
      path: '/categories/$id/edit'
      fullPath: '/admin/categories/$id/edit'
      preLoaderRoute: typeof AdminCategoriesIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface StorefrontRouteRouteChildren {
  StorefrontAboutRoute: typeof StorefrontAboutRoute
  StorefrontCheckoutRoute: typeof StorefrontCheckoutRoute
  StorefrontOrderConfirmedRoute: typeof StorefrontOrderConfirmedRoute
  StorefrontIndexRoute: typeof StorefrontIndexRoute
  StorefrontCategoriesSlugRoute: typeof StorefrontCategoriesSlugRoute
  StorefrontProductsSlugRoute: typeof StorefrontProductsSlugRoute
  StorefrontCategoriesIndexRoute: typeof StorefrontCategoriesIndexRoute
  StorefrontProductsIndexRoute: typeof StorefrontProductsIndexRoute
}

const StorefrontRouteRouteChildren: StorefrontRouteRouteChildren = {
  StorefrontAboutRoute: StorefrontAboutRoute,
  StorefrontCheckoutRoute: StorefrontCheckoutRoute,
  StorefrontOrderConfirmedRoute: StorefrontOrderConfirmedRoute,
  StorefrontIndexRoute: StorefrontIndexRoute,
  StorefrontCategoriesSlugRoute: StorefrontCategoriesSlugRoute,
  StorefrontProductsSlugRoute: StorefrontProductsSlugRoute,
  StorefrontCategoriesIndexRoute: StorefrontCategoriesIndexRoute,
  StorefrontProductsIndexRoute: StorefrontProductsIndexRoute,
}

const StorefrontRouteRouteWithChildren = StorefrontRouteRoute._addFileChildren(
  StorefrontRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCategoriesNewRoute: typeof AdminCategoriesNewRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminCategoriesIdEditRoute: typeof AdminCategoriesIdEditRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCategoriesNewRoute: AdminCategoriesNewRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminCategoriesIdEditRoute: AdminCategoriesIdEditRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  StorefrontRouteRoute: StorefrontRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiAdminUploadAuthRoute: ApiAdminUploadAuthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
